In [1]:
import numpy as np
import pandas as pd
from keras import Sequential,layers,models
import keras

Using TensorFlow backend.


In [2]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")


In [3]:
model=models.Sequential()
model.add()
model.add(layers.Dense(512,input_shape=(28*28,),activation='relu'))
model.add(layers.Dense(10,activation="softmax"))
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])


In [4]:
x=train.drop('label',axis=1)
x=x.astype('float32')/255
y=train.label
cate=keras.utils.to_categorical(y)
print(cate)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,cate,test_size=0.3,random_state=0)


In [12]:
model.fit(xtrain,ytrain,epochs=20,batch_size=128)

Epoch 1/5
29400/29400 [==============================] - 3s 111us/step - loss: 0.0021 - accuracy: 0.9995
Epoch 2/5
29400/29400 [==============================] - 3s 112us/step - loss: 0.0016 - accuracy: 0.9997
Epoch 3/5
29400/29400 [==============================] - 3s 112us/step - loss: 0.0012 - accuracy: 0.9997
Epoch 4/5
29400/29400 [==============================] - 3s 112us/step - loss: 0.0011 - accuracy: 0.9998
Epoch 5/5
29400/29400 [==============================] - 3s 112us/step - loss: 5.3409e-04 - accuracy: 0.9999


In [13]:
loss,accuracy=model.evaluate(xtest,ytest)
print("accuracy ",accuracy)

12600/12600 [==============================] - 1s 84us/step
accuracy  0.9842857122421265


In [14]:
test=test.astype('float32')/255
predicted=model.predict(test)


In [15]:
fin=np.argmax(predicted,axis=1)